name: starter-snake-haskell
version: 1.1.0
synopsis: A Haskell Battlesnake starter
description: See README at <https://github.com/ccntrq/starter-snake-haskell>
category: Game, Web
license: BSD3
author: "Alexander Pankoff <ccntrq@screenri.de"
maintainer: "Alexander Pankoff <ccntrq@screenri.de>"
copyright: "2021 Alexander Pankoff"
github: ccntrq/starter-snake-haskell

extra-source-files:
  - README.md
  - CHANGELOG.md
  - LICENSE

dependencies:
  - base >= 4.13 && < 5
  - aeson >= 1.4 && < 3
  - containers >= 0.6 && < 1
  - scotty >= 0.11 && < 1
  - text >= 1.2 && < 2

library:
  source-dirs: src
  ghc-options:
    - -Wall
  default-extensions:
    - OverloadedStrings

executables:
  starter-snake-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    default-extensions:
      - OverloadedStrings
    dependencies:
      - starter-snake-haskell

tests:
  starter-snake-haskell:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - starter-snake-haskell
